name: CI-Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v4

    - name: Extract DOCKER_TAG using tag name
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "DOCKER_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

    - name: Extract REPO_NAME
      run: |
        REPO_NAME=$(echo "$GITHUB_REPOSITORY" | cut -d'/' -f2)
        echo "GITHUB_REPOSITORY_NAME=$REPO_NAME" >> $GITHUB_ENV
    
    - name: Use default DOCKER_TAG
      if: startsWith(github.ref, 'refs/tags/') != true
      run: |
        echo "DOCKER_TAG=latest" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - uses: docker/build-push-action@v4
      with:
        push: true
#        tags: ${{ github.repository }}:${{ env.DOCKER_TAG }}
        tags: ${{ vars.DOCKER_USERNAME }}/${{ env.GITHUB_REPOSITORY_NAME }}:${{ env.DOCKER_TAG }}
    
    - name: Send Compile action
      run: |
        export DISPATCH_ACTION="$(echo run_build)"
        echo "NEW_DISPATCH_ACTION=$DISPATCH_ACTION" >> $GITHUB_ENV

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v3
      with:
        repository: ${{ github.repository_owner }}/orbisdev-sdkvanilla
        token: ${{ secrets.DISPATCH_TOKEN }}
        event-type: ${{ env.NEW_DISPATCH_ACTION }}
        client-payload: '{"ref": "${{ github.ref }}"}'
